name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "88c85034968b4797b4f4b445fe61b602" },
  { binding = "SHARE", id = "12b4107e003e4406bbf638e4404d1452" }
]